# Default values for enviroplus-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

pms5003:
  # Set to true to enable pms5003 particles sensor
  enabled: false

image:
  repository: ghcr.io/tijmenvandenbrink/enviroplus_exporter
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  # Overrides the arguments that are passed to the enviroplus_exporter
  #
  # usage: enviroplus_exporter.py [-h] [-b ADDRESS] [-p PORT] [-f FACTOR] [-e ENVIRO] [-d DEBUG] [-i INFLUXDB] [-l LUFTDATEN]
  # options:
  #   -h, --help            show this help message and exit
  #   -b ADDRESS, --bind ADDRESS
  #                         Specify alternate bind address [default: 0.0.0.0]
  #   -p PORT, --port PORT  Specify alternate port [default: 8000]
  #   -f FACTOR, --factor FACTOR
  #                         The compensation factor to get better temperature results when the Enviro+ pHAT is too close to the Raspberry Pi board
  #   -e ENVIRO, --enviro ENVIRO
  #                         Device is an Enviro (not Enviro+) so don't fetch data from gas and particulate sensors as they don't exist
  #   -d DEBUG, --debug DEBUG
  #                         Turns on more verbose logging, showing sensor output and post responses [default: false]
  #   -i INFLUXDB, --influxdb INFLUXDB
  #                         Post sensor data to InfluxDB [default: false]
  #   -l LUFTDATEN, --luftdaten LUFTDATEN
  #                         Post sensor data to Luftdaten [default: false]
  #args: ["--bind=0.0.0.0", "--port=8000", ]

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  privileged: true

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
